version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskrios-backend
    environment:
      - DB_HOST=postgres
      - DB_USER=san
      - DB_PASSWORD=santy401
      - DB_NAME=TasksRios
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "sleep 10 && npm start"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=san
      - POSTGRES_PASSWORD=santy401
      - POSTGRES_DB=TasksRios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U san -d TasksRios"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
