version: '3.8'
services:
  app:
    image: taskrios-backend
    network_mode: "host"
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=san
      - DB_PASSWORD=santy401
      - DB_NAME=TasksRios
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && npm start"

  postgres:
    image: postgres:latest
    network_mode: "host"
    environment:
      - POSTGRES_USER=san
      - POSTGRES_PASSWORD=santy401
      - POSTGRES_DB=TasksRios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U san"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

